# Generated by Django 3.1.1 on 2020-11-11 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='ISO-639-1 language codes for supported languages for translation. See <a href="https://py-googletrans.readthedocs.io/en/latest/#googletrans-languages">googletrans.LANGUAGES</a>.', max_length=5, verbose_name='Translation Key')),
                ('english_name', models.CharField(max_length=20)),
                ('native_name', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=20)),
                ('duolingo_learners', models.PositiveIntegerField(help_text='The amount of learners this language course has on Duolingo. See <a href="https://www.duolingo.com/courses">Duolingo Courses</a>.')),
                ('flag_flat', models.ImageField(upload_to='flags/flat')),
                ('flag_button', models.ImageField(upload_to='flags/button')),
            ],
            options={
                'ordering': ['english_name'],
            },
        ),
        migrations.CreateModel(
            name='LearningLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='Experience')),
                ('foreign_language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.foreignlanguage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'foreign_language'],
            },
        ),
    ]
