# Generated by Django 3.1.1 on 2020-11-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201111_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningLanguage',
        ),
        migrations.DeleteModel(
            name='uForeignLanguage',
        ),
    ]
