# Generated by Django 3.1.1 on 2021-05-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201230_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(help_text='A publicly displayed name. Does not need to be unique.', max_length=20),
        ),
    ]
