# Generated by Django 3.1.1 on 2020-11-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='ISO-639-1 language codes for supported languages for translation. See <a href="https://py-googletrans.readthedocs.io/en/latest/#googletrans-languages">googletrans.LANGUAGES</a>.', max_length=5, verbose_name='Translation Key')),
                ('english_name', models.CharField(max_length=20)),
                ('native_name', models.CharField(max_length=20)),
                ('note', models.CharField(blank=True, max_length=20)),
                ('duolingo_learners', models.PositiveIntegerField(help_text='The amount of learners this language course has on Duolingo. See <a href="https://www.duolingo.com/courses">Duolingo Courses</a>.')),
                ('flag_flat', models.ImageField(upload_to='flags/flat')),
                ('flag_button', models.ImageField(upload_to='flags/button')),
            ],
            options={
                'ordering': ['english_name'],
            },
        ),
    ]
