# Generated by Django 3.1.1 on 2020-11-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_learninglanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='key',
            field=models.CharField(help_text='ISO-639-1 language codes for supported languages for translation. See <a href="https://py-googletrans.readthedocs.io/en/latest/#googletrans-languages">googletrans.LANGUAGES</a>.', max_length=5),
        ),
        migrations.CreateModel(
            name='TranslatableWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=50, unique=True)),
                ('categories', models.ManyToManyField(to='language.Category')),
            ],
            options={
                'ordering': ['english_word'],
            },
        ),
    ]
