# Generated by Django 3.1.1 on 2020-11-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0004_auto_20201111_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Word categories'},
        ),
    ]
