# Generated by Django 3.1.1 on 2020-12-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0005_auto_20201111_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignlanguage',
            name='flag_button',
            field=models.ImageField(upload_to='language_flags/button'),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='flag_flat',
            field=models.ImageField(upload_to='language_flags/flat'),
        ),
    ]
