# Generated by Django 3.1.1 on 2020-12-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0006_auto_20201220_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignlanguage',
            name='flag_button',
        ),
        migrations.RemoveField(
            model_name='foreignlanguage',
            name='flag_flat',
        ),
        migrations.AddField(
            model_name='foreignlanguage',
            name='flag',
            field=models.ImageField(default='', upload_to='language_flags'),
            preserve_default=False,
        ),
    ]
