# Generated by Django 3.1.1 on 2020-12-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0007_auto_20201228_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninglanguage',
            name='xp',
        ),
    ]
