# Generated by Django 3.1.1 on 2020-12-30 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0012_learninglanguage_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninglanguage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='learninglanguage',
            name='date_started',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
