# Generated by Django 3.1.1 on 2021-01-20 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0014_auto_20210119_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninglanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_languages', to=settings.AUTH_USER_MODEL),
        ),
    ]
