# Generated by Django 3.1.1 on 2021-01-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0016_auto_20210121_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='foreign_language',
            new_name='language',
        ),
    ]
