# Generated by Django 3.1.1 on 2021-01-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0017_auto_20210122_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translatableword',
            options={'ordering': ['english_word']},
        ),
        migrations.RenameField(
            model_name='foreignlanguage',
            old_name='native_name',
            new_name='foreign_name',
        ),
    ]
