# Generated by Django 3.1.1 on 2021-01-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0018_auto_20210122_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='foreignlanguage',
            name='uses_latin_script',
            field=models.BooleanField(default=True),
        ),
    ]
