# Generated by Django 3.1.1 on 2021-01-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0019_foreignlanguage_uses_latin_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='language',
            new_name='foreign_language',
        ),
        migrations.AddField(
            model_name='translation',
            name='foreign_word',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='uses_latin_script',
            field=models.BooleanField(default=True, help_text='The English language uses Latin script, an Alphabetical <a href="https://en.wikipedia.org/wiki/Writing_system"> writing system</a>.<br>Ensure this field is False for languages which use different scripts (e.g. Russian: Cyrillic) or systems (e.g. Japanese: Kana, Kanji).', verbose_name='Uses Latin script'),
        ),
    ]
