# Generated by Django 3.1.1 on 2021-01-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0020_auto_20210123_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['foreign_language', 'translatable_word']},
        ),
    ]
