# Generated by Django 3.1.1 on 2021-01-24 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0021_auto_20210123_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
