# Generated by Django 3.1.1 on 2021-02-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('language', '0022_translation_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('delta', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('test_count', models.PositiveIntegerField(default=0)),
                ('test_correct', models.PositiveIntegerField(default=0)),
                ('p_translate', models.FloatField(default=0)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_tracking', to='language.translation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_tracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
