# Generated by Django 3.1.1 on 2021-02-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0023_learningtracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtracking',
            name='p_translate',
        ),
        migrations.AlterField(
            model_name='learningtracking',
            name='delta',
            field=models.PositiveIntegerField(default=0, verbose_name='Time delta'),
        ),
    ]
