# Generated by Django 3.1.1 on 2021-02-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0024_auto_20210209_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningtracking',
            options={'verbose_name': ' Learning Tracking', 'verbose_name_plural': ' Learning Tracking'},
        ),
        migrations.RemoveField(
            model_name='learningtracking',
            name='delta',
        ),
        migrations.AddField(
            model_name='learningtracking',
            name='previous_interaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='language.learningtracking'),
        ),
        migrations.AlterField(
            model_name='learningtracking',
            name='read_count',
            field=models.PositiveIntegerField(default=0, help_text='Total times the user has interacted with this word during <b>reading</b>'),
        ),
        migrations.AlterField(
            model_name='learningtracking',
            name='test_correct',
            field=models.PositiveIntegerField(default=0, help_text='Total times the user has <b>correctly</b> translated this word during <b>testing</b>'),
        ),
        migrations.AlterField(
            model_name='learningtracking',
            name='test_count',
            field=models.PositiveIntegerField(default=0, help_text='Total times the user has interacted with this word during <b>testing</b>'),
        ),
        migrations.AlterField(
            model_name='learningtracking',
            name='time',
            field=models.DateTimeField(auto_now=True, help_text='Time when the user interacted with this word'),
        ),
    ]
