# Generated by Django 3.1.1 on 2021-02-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0027_auto_20210209_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtracking',
            name='previous_interaction',
        ),
        migrations.AddField(
            model_name='learningtracking',
            name='prev',
            field=models.ForeignKey(blank=True, help_text='The previous interaction the user had with this word, if any', null=True, on_delete=django.db.models.deletion.CASCADE, to='language.learningtracking', verbose_name='Previous Interaction'),
        ),
    ]
