# Generated by Django 3.1.1 on 2021-02-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0031_auto_20210209_1847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningtracking',
            options={'ordering': ['time'], 'verbose_name': ' Learning Tracking', 'verbose_name_plural': ' Learning Tracking'},
        ),
    ]
