# Generated by Django 3.1.1 on 2021-02-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0032_auto_20210209_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtracking',
            name='p_trans',
            field=models.FloatField(default=0, help_text='Proportion of tests where the user has <b>correctly</b> translated this word', verbose_name='Proportion Translated'),
        ),
    ]
