# Generated by Django 3.1.1 on 2021-02-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0033_learningtracking_p_trans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtracking',
            name='p_trans',
        ),
    ]
