# Generated by Django 3.1.1 on 2021-02-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0035_auto_20210209_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningtracking',
            name='learning_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_tracking', to='language.learninglanguage'),
        ),
    ]
