# Generated by Django 3.1.1 on 2021-02-16 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0036_learningtracking_learning_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningTracking',
        ),
    ]
