# Generated by Django 3.1.1 on 2021-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0037_delete_learningtracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='translatableword',
            name='synonyms',
            field=models.ManyToManyField(related_name='translatable_words', to='language.Synonym'),
        ),
    ]
