# Generated by Django 3.1.1 on 2021-04-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0038_auto_20210317_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translatableword',
            name='synonyms',
        ),
        migrations.AddField(
            model_name='synonym',
            name='translatable_words',
            field=models.ManyToManyField(related_name='synonyms', to='language.TranslatableWord'),
        ),
    ]
