# Generated by Django 3.1.1 on 2021-04-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0039_auto_20210426_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synonym',
            name='translatable_words',
        ),
        migrations.AddField(
            model_name='translatableword',
            name='synonyms',
            field=models.ManyToManyField(related_name='translatable_words', to='language.Synonym'),
        ),
    ]
