# Generated by Django 3.1.1 on 2021-05-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0040_auto_20210426_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignlanguage',
            name='key',
            field=models.CharField(help_text='ISO-639-1 language codes for supported languages for translation. See <a href="https://py-googletrans.readthedocs.io/en/latest/#googletrans-languages">googletrans.LANGUAGES</a>.', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='foreignlanguage',
            name='uses_latin_script',
            field=models.BooleanField(default=True, help_text='The English language uses Latin script, an Alphabetical <a href="https://en.wikipedia.org/wiki/Writing_system"> writing system</a>.<br>Ensure this field is False for languages which use different scripts (e.g. Russian: Cyrillic) or writing systems (e.g. Japanese: Kana, Kanji).', verbose_name='Uses Latin script'),
        ),
    ]
