# Generated by Django 3.1.1 on 2020-10-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=1000)),
                ('pub_date', models.DateField(verbose_name='Date Published')),
                ('publisher', models.CharField(max_length=100)),
                ('isbn', models.CharField(help_text='A 10 or 13 character <a href="https://www.isbn-international.org/content/what-isbn">ISBN</a>. This is <a href="https://en.wikipedia.org/wiki/International_Standard_Book_Number#Overview">different for separate editions and variations</a> of the same book.', max_length=13, verbose_name='ISBN')),
                ('author', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='read.author')),
                ('genre', models.ManyToManyField(to='read.Genre')),
            ],
            options={
                'ordering': ['title', '-pub_date'],
            },
        ),
    ]
