# Generated by Django 3.1.1 on 2020-10-02 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_auto_20201002_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name', 'date_of_birth']},
        ),
    ]
