# Generated by Django 3.1.1 on 2020-12-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_auto_20201220_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'forename', 'middle_names']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='other_names',
        ),
        migrations.AddField(
            model_name='author',
            name='middle_names',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
