# Generated by Django 3.1.1 on 2020-10-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_auto_20201002_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Tag',
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'author', '-pub_date']},
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(max_length=50, to='read.Tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='A 10 or 13 character <a href="https://www.isbn-international.org/content/what-isbn">ISBN</a>. This is <a href="https://en.wikipedia.org/wiki/International_Standard_Book_Number#Overview">different for separate editions and variations</a> of the same book.', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
