# Generated by Django 3.1.1 on 2020-12-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0004_auto_20201220_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='no',
            field=models.SmallIntegerField(default=0, verbose_name='Number'),
            preserve_default=False,
        ),
    ]
