# Generated by Django 3.1.1 on 2020-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0005_auto_20201002_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, max_length=50, null=True, to='read.Tag'),
        ),
    ]
