# Generated by Django 3.1.1 on 2020-12-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0006_auto_20201222_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.SmallIntegerField(editable=False),
        ),
    ]
