# Generated by Django 3.1.1 on 2020-10-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0007_auto_20201002_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='words',
            field=models.ManyToManyField(blank=True, to='read.TranslatableWord'),
        ),
    ]
