# Generated by Django 3.1.1 on 2020-12-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0008_auto_20201222_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['book', 'number']},
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs'),
        ),
        migrations.AlterField(
            model_name='book',
            name='source_url',
            field=models.URLField(verbose_name='Source URL'),
        ),
    ]
