# Generated by Django 3.1.1 on 2020-10-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0009_auto_20201002_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='translatableword',
            name='english_word',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
