# Generated by Django 3.1.1 on 2020-12-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0009_auto_20201222_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs', verbose_name='PDF'),
        ),
    ]
