# Generated by Django 3.1.1 on 2020-10-02 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0010_auto_20201002_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
    ]
