# Generated by Django 3.1.1 on 2020-12-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0011_auto_20201222_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='book_covers/default.jpg', upload_to='book_covers'),
        ),
    ]
