# Generated by Django 3.1.1 on 2020-11-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0013_auto_20201003_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='uCategory',
        ),
        migrations.RenameModel(
            old_name='TranslatableWord',
            new_name='uTranslatableWord',
        ),
    ]
