# Generated by Django 3.1.1 on 2020-11-11 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0014_auto_20201111_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utranslatableword',
            name='categories',
        ),
        migrations.DeleteModel(
            name='uCategory',
        ),
        migrations.DeleteModel(
            name='uTranslatableWord',
        ),
    ]
