# Generated by Django 3.1.1 on 2021-05-03 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0014_auto_20210502_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, help_text='A PDF file representing the book. This can be blank. Used to generate Pages.', null=True, upload_to='book_pdfs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF'),
        ),
        migrations.AlterField(
            model_name='page',
            name='number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
