# Generated by Django 3.1.1 on 2021-02-15 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0036_learningtracking_learning_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('READ', 'Reading'), ('TEST', 'Testing')], default='READ', max_length=4)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(help_text='May be null if the session is not ended in a proper manner.', null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.PositiveIntegerField(default=0, help_text='Total times the user has interacted with this translation during <b>reading</b>')),
                ('test_count', models.PositiveIntegerField(default=0, help_text='Total times the user has interacted with this translation during <b>testing</b>')),
                ('test_correct', models.PositiveIntegerField(default=0, help_text='Total times the user has <b>correctly</b> translated this word during <b>testing</b>')),
                ('prev', models.ForeignKey(blank=True, help_text='Previous interaction <b>(LearningTrace object)</b> the user had with this translation, if any', null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.learningtrace')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='tracking.session')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_traces', to='language.translation')),
            ],
        ),
    ]
