# Generated by Django 3.1.1 on 2021-02-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0036_learningtracking_learning_language'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='learning_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='language.learninglanguage'),
        ),
        migrations.AlterField(
            model_name='learningtrace',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='language.translation'),
        ),
    ]
