# Generated by Django 3.1.1 on 2021-02-15 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0036_learningtracking_learning_language'),
        ('tracking', '0003_auto_20210215_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='langysession',
            options={'ordering': ['start_time']},
        ),
        migrations.RemoveField(
            model_name='langysession',
            name='learning_language',
        ),
        migrations.AddField(
            model_name='langysession',
            name='foreign_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='language.foreignlanguage'),
        ),
    ]
