# Generated by Django 3.1.1 on 2021-02-16 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0036_learningtracking_learning_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0004_auto_20210215_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningtrace',
            options={'ordering': ['session__start_time', 'translation__translatable_word__english_word']},
        ),
        migrations.AddField(
            model_name='learningtrace',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='langysession',
            name='foreign_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='language.foreignlanguage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='langysession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.customuser'),
            preserve_default=False,
        ),
    ]
