# Generated by Django 3.1.1 on 2021-02-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0013_auto_20201228_0134'),
        ('tracking', '0005_auto_20210216_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='langysession',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='read.book'),
        ),
    ]
