# Generated by Django 3.1.1 on 2021-03-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_langysession_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtrace',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='learningtrace',
            name='test_correct',
        ),
        migrations.RemoveField(
            model_name='learningtrace',
            name='test_count',
        ),
        migrations.AddField(
            model_name='learningtrace',
            name='interacted',
            field=models.PositiveIntegerField(default=0, help_text='Amount of times the user has <b>interacted</b> with this translation during <b>reading</b>'),
        ),
        migrations.AddField(
            model_name='learningtrace',
            name='seen',
            field=models.PositiveIntegerField(default=0, help_text='Amount of times the user has <b>seen</b> this translation during <b>reading</b>'),
        ),
        migrations.AddField(
            model_name='learningtrace',
            name='tested',
            field=models.PositiveIntegerField(default=0, help_text='Amount of times the user has been <b>tested</b> on this translation'),
        ),
        migrations.AddField(
            model_name='learningtrace',
            name='tested_correct',
            field=models.PositiveIntegerField(default=0, help_text='Amount of times the user has <b>correctly</b> translated this word during <b>testing</b>'),
        ),
    ]
