# Generated by Django 3.1.1 on 2021-03-17 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_auto_20210310_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langysession',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='learningtrace',
            name='prev',
            field=models.ForeignKey(blank=True, help_text="User's previous <b>LearningTrace</b> for this translation, if any", null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.learningtrace'),
        ),
        migrations.AlterField(
            model_name='learningtrace',
            name='seen',
            field=models.PositiveIntegerField(default=0, help_text='Amount of times the user has <b>seen</b> this translation during <b>reading and testing</b>'),
        ),
    ]
