# Generated by Django 3.1.1 on 2021-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20210317_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningtrace',
            old_name='tested_correct',
            new_name='correct',
        ),
    ]
